name: verify

on:
  pull_request:
    branches: [ master ]

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      uses: actions/setup-node@v1
      with:
        node-version: 12.20.0
    - run: npm ci
    - run: npm test
